# Generated by Django 4.0.6 on 2022-08-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='startUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('startUpName', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('fund_needed', models.IntegerField()),
                ('contactNumber', models.IntegerField()),
                ('email', models.BooleanField()),
            ],
        ),
    ]
