# Generated by Django 4.1 on 2022-08-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='fund_needed',
        ),
        migrations.AddField(
            model_name='startup',
            name='funds',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startup',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
