# Generated by Django 4.1 on 2022-08-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_startup_fund_needed_startup_funds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('startUpName', models.CharField(max_length=40)),
                ('contactNumber', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
