# Generated by Django 4.1 on 2022-08-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='loss', max_length=254),
            preserve_default=False,
        ),
    ]
